### ISSUE TITLE
Use of data ready bit with Infrared_PD algo

### ISSUE THREAD

**Issue by jk0010** [STMicroelectronics/X-CUBE-MEMS1#10]
I see that in the PresenceDetection_STHS34PF80 example app the data collection method is implemented by changing the TIM3 period based on the desired ODR. Is the data ready bit being used in this example like when using the embedded algorithm. Is the data ready bit preferred for collecting data over using a timer?

**Comment by PetrSterbaST** [comment]
Some algorithms require precise timing of data feeding so we use timer for all algorithms even if in case of presence detection the exact frequency is not really crucial, you can use data ready bit if you prefer.

**Comment by jk0010** [comment]
Could there be an issue when the timer comes around to run the InfraredPD algo and the data in TAMBIENT or TOBJECT is not ready yet? Could either LSB or MSB of tamb/tobj contain old data from a previous reading? This is one reason I was thinking to use drdy instead of a timer. I am using BDU to avoid this once I start reading data from the register.

**Comment by PetrSterbaST** [comment]
If you use BDU, then it cannot happen that you'd read higher and lower byte from different samples. The only thing that can happen when using timer is that when new data are not ready yet you'll send previous data to the algorithm and it's not a problem. Of course by using DRDY you'll avoid this.
