### ISSUE TITLE
Motion Library: launch on STM32MP

### ISSUE THREAD

**Issue by AlexandrShipovsky** [STMicroelectronics/X-CUBE-MEMS1#2]
Hi everyone!
I want to use Motion Libraries on STM32MP (only Cortex-M4 core), but in CubeMX i get warning: "This pack does not support STM32MP1 Series".

Describe the set-up:

 My board: STM32MP157A-DK1
 My IDE: STM32CubeIDE 1.7.0
 Libraries: MotionFX,MotionMC,MotionVC

The STM32MP has the same Cortex-M4 core as in many other microcontrollers running these libraries. How can I solve the problem?

**Comment by cparata** [comment]
Hi @AlexandrShipovsky ,
thanks for the question. Unfortunately, I confirm that at the moment the cortex-m4 motion libraries cannot work on the cortex-m4 core of the MP1 series. In future, the motion libraries will be updated to support also this use case.
Best Regards,
Carlo

**Comment by AlexandrShipovsky** [comment]
@cparata okay, thank you for answer! I hope it will be update
