### ISSUE TITLE
Compatibility question

### ISSUE THREAD

**Issue by tomy983** [STMicroelectronics/X-CUBE-MEMS1#5]
Hello, just a question here. I'm totally new to the stm32 platform and was looking to get a dev board. I would like to try some of the examples from this repository to get a feeling of how things works. I understand there are examples available for a NUCLEO-L476RG + X-NUCLEO-IKS01A2, but I was looking to buy the B-L475E-IOT01A Discovery. I've notice there is not much difference in the MCU (lcd pins only??) and the set of sensors is not all that different. 
My question is: will I be able to run the examples on the B-L475E-IOT01A Discovery without too much trouble being a total beginner on this platform?
Thank you

**Comment by cparata** [comment]
Hello @tomy983,
the example that you can find in the package are for specific Nucleo boards and the expansion boards. Of course, you can reuse the drivers also for the B-L475E-IOT01A Discovery boards, but there are several software modules that should be adapted. Another option is to use STM32CubeMX tool and the X-CUBE-MEMS1 CMSIS pack to generate some custom MEMS applications for the B-L475E-IOT01A, but for sure you need to have some experience with STM32CubeMX and STM32 boards. If you are a total beginner, I suggest to start with Nucleo-F401RE and X-NUCLEO-IKS01A3 expansion board.
Best Regards,
Carlo
