### ISSUE TITLE
How to get the MotionSensor Libraries working on other ARM Controllers?

### ISSUE THREAD

**Issue by ghost** [STMicroelectronics/X-CUBE-MEMS1#9]
How to get the MotionSensor Libraries working on other ARM Controllers?

I ported the MotionMC and MotionEC Lib (want to using the LSM303AGR) to our nRF52 but it get stuck inside MotionMC_manager_init function.

I think u set everything correct:

"-mfloat-abi=hard -mfpu=fpv4-sp-d16",
"-DFLOAT_ABI_HARD",
"-l:MotionMC_CM4F_wc32_ot_hard.a",
"-l:MotionEC_CM4F_wc32_ot_hard.a",

Or is it general impossible to port to other MCUs?

**Comment by cparata** [comment]
Hello @jul-nc ,
basically, you cannot use these libraries with other MCUs different from STM32 for license reasons. If you give a look at MotionMC license [here](https://github.com/STMicroelectronics/X-CUBE-MEMS1/blob/main/Middlewares/ST/STM32_MotionMC_Library/LICENSE.md) (but it is the same for all the other motion libraries), you will find that the library can be used only with STM32 and ST MEMS sensors.
So, you cannot use these libraries with nRF52 MCUs.
Best Regards,
Carlo
